/* Operations & Pricing — printable documents generated from the shipment JSON (English, as in trade practice) */
(function () {
  const L = TS.L, esc = TS.esc;
  const OPS = window.OPS;
  const co = () => OPS.company;
  const head = (title, sub) => `<div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><b style="font-size:15px;color:#0b4f71">⚓ ${esc(co().name)}</b><br><small>${esc(co().address)} · ${esc(co().phone)} · VAT ${esc(co().vat)}</small></div><div style="text-align:right"><b style="font-size:16px">${esc(title)}</b>${sub ? '<br><small>' + sub + '</small>' : ''}</div></div><hr>`;
  const kv = (rows) => `<table><tbody>${rows.map(([k, v]) => `<tr><th style="width:200px">${esc(k)}</th><td>${v}</td></tr>`).join('')}</tbody></table>`;
  const party = (p) => (p ? `<b>${esc(p.name)}</b><br>${esc(p.address || '')}` : '');
  const box = (lbl, html) => `<div><div class="lbl">${esc(lbl)}</div>${html}</div>`;
  const footer = `<p style="margin-top:14px"><small>Training document generated by the Training Shipping simulator — fictional companies, sample figures.</small></p>`;

  function jobfile(s) {
    const j = s.jobFile;
    return `<div class="doc">${head('JOB FILE', s.id)}${kv([['Client', esc(j.client)], ['Direction', esc(s.direction)], ['Shipper', esc(j.shipper)], ['Consignee', esc(j.consignee)], ['Incoterm', esc(j.incoterm + ' ' + j.namedPlace)], ['Route', esc(OPS.portName(j.pol) + ' → ' + OPS.portName(j.pod)) + ' (' + esc(j.scope) + ')'], ['Commodity', esc(j.commodity) + ' — HS ' + esc(j.hs)], ['Packages', esc(j.packages + ' ' + j.pkgType)], ['Gross weight', TS.num(j.grossKg, 0) + ' kg'], ['Volume', TS.num(j.cbm) + ' CBM'], ['Equipment', '1 × ' + esc(j.equipment)], ['DG', esc(j.dg)], ['Cargo ready', TS.fmtDate(j.readyDate)], ['Invoice value', 'USD ' + TS.num(j.value)]])}${footer}</div>`;
  }

  function quotation(s) {
    const q = s.quotation, sc = OPS.sc(s);
    const act = q.lines.filter((l) => l.group !== 'optional' || q.insurance);
    return `<div class="doc">${head('QUOTATION', esc(q.no) + '<br>Date ' + TS.fmtDate(q.date, false) + ' · Valid until ' + TS.fmtDate(q.validTo, false))}
      <p><b>To:</b> ${party(sc.client)}<br>Attn: ${esc(sc.client.contact)}</p>
      <p>1 × ${esc(s.jobFile.equipment)} — ${esc(OPS.portName(s.jobFile.pol))} → ${esc(OPS.portName(s.jobFile.pod))} — ${esc(s.jobFile.incoterm)} ${esc(s.jobFile.namedPlace)} — via ${esc(s.rates.selected.carrierName)}, T/S ${esc(s.rates.selected.ts)}, transit about ${s.rates.selected.transit} days</p>
      <table><thead><tr><th>Code</th><th>Description</th><th>Basis</th><th class="num">USD</th><th>VAT</th></tr></thead><tbody>
      ${act.map((l) => `<tr><td>${l.code}</td><td>${esc(l.desc.en || l.desc)}</td><td>${l.basis === 'cntr' ? 'per ' + esc(s.jobFile.equipment) : 'per B/L'}</td><td class="num">${TS.num(l.sell)}</td><td>${l.vat ? '11%' : 'exempt'}</td></tr>`).join('')}
      <tr class="total"><td></td><td>Sub-total</td><td></td><td class="num">${TS.num(q.totals.sell)}</td><td></td></tr>
      <tr><td></td><td>VAT 11% on USD ${TS.num(q.totals.vatBase)}</td><td></td><td class="num">${TS.num(q.totals.vat)}</td><td></td></tr>
      <tr class="total"><td></td><td>TOTAL</td><td></td><td class="num">${TS.num(q.totals.grand)}</td><td></td></tr></tbody></table>
      ${q.deposit ? `<p><b>Container deposit:</b> USD ${TS.num(q.deposit, 0)} refundable, payable to the line’s agent before D/O (not included above).</p>` : ''}
      <p><b>Conditions:</b></p><ul>${q.conditions.map((c) => '<li>' + esc(c) + '</li>').join('')}</ul>${footer}</div>`;
  }

  function so(s) {
    const b = s.booking;
    return `<div class="doc">${head('BOOKING CONFIRMATION / SHIPPING ORDER', esc(b.carrierName) + ' · ' + esc(b.no))}${kv([['Booking no.', '<b class="mono">' + esc(b.no) + '</b>'], ['Booking party', esc(co().name)], ['Vessel / voyage', esc(b.vessel + ' / ' + b.voyage)], ['POL → POD', esc(b.pol + ' → ' + b.pod) + ' (T/S ' + esc(b.ts) + ')'], ['Equipment', b.qty + ' × ' + esc(b.equipment)], ['ETD / ETA', TS.fmtDate(b.etd) + ' / ' + TS.fmtDate(b.eta)], ['ERD', TS.fmtDate(b.cutoffs.erd)], ['SI cutoff', TS.fmtDate(b.cutoffs.si) + ' 12:00'], ['VGM cutoff', TS.fmtDate(b.cutoffs.vgm) + ' 12:00'], ['CY cutoff', '<b>' + TS.fmtDate(b.cutoffs.cy) + ' 16:00</b>'], ['Empty pickup', esc(b.depot)], ['Free time at POD', b.freeDays + ' days combined DEM/DET'], ['Freight', esc(b.freightTerms)]])}
      <p><small>Containers arriving after CY cutoff will be rolled. Late SI/VGM subject to fees. Empty release valid 7 days.</small></p>${footer}</div>`;
  }

  function vgm(s) {
    const e = s.equipment;
    return `<div class="doc">${head('VERIFIED GROSS MASS DECLARATION (SOLAS VI/2)', esc(s.booking.no))}${kv([['Shipper', esc(e.vgmSignedBy)], ['Booking no.', esc(s.booking.no)], ['Container no.', esc(e.containerNo) + ' (' + esc(e.type) + ')'], ['Seal no.', esc(e.seal)], ['Method', e.vgmMethod === 'M1' ? 'Method 1 — weighing the packed container' : 'Method 2 — sum of cargo, packing, dunnage and tare'], ['Cargo gross', TS.num(s.jobFile.grossKg, 0) + ' kg'], ['Dunnage/lashing', TS.num(e.dunnageKg, 0) + ' kg'], ['Tare', TS.num(e.tare, 0) + ' kg'], ['VGM', '<b>' + TS.num(e.vgm, 0) + ' kg</b>'], ['Submitted', TS.fmtDate(e.vgmSubmitted)]])}<p>Authorised signature: ____________________</p>${footer}</div>`;
  }

  function si(s) {
    const x = s.documents.si, p = x.parties;
    return `<div class="doc">${head('SHIPPING INSTRUCTIONS', 'Booking ' + esc(x.bk) + ' · submitted ' + TS.fmtDate(x.submitted, false))}${kv([['Shipper', esc(p.mblShipper)], ['Consignee', esc(p.mblConsignee)], ['Notify', esc(p.mblNotify)], ['Container / seal', esc(x.cn + ' / ' + x.seal)], ['Packages', esc(x.pk)], ['Description', esc(x.desc)], ['Gross weight', TS.num(x.kg, 0) + ' kg'], ['Measurement', TS.num(x.cbm) + ' CBM'], ['Freight', esc(x.ft)]])}${footer}</div>`;
  }

  function bl(s, house) {
    const b = s.documents.bl, p = OPS.blParties(s), j = s.jobFile, e = s.equipment, bk = s.booking;
    const issued = !!b.issuedOn;
    const shipper = house ? p.hblShipper : p.mblShipper, cons = house ? p.hblConsignee : p.mblConsignee, notify = house ? p.hblNotify : p.mblNotify;
    const issuer = house ? co().name + ' (as carrier, NVOCC)' : bk.carrierName;
    const type = house ? b.hblType || 'Original' : b.mblType || 'Seaway bill';
    const ft = house ? (s.direction === 'import' ? 'FREIGHT COLLECT' : 'FREIGHT PREPAID') : 'FREIGHT ' + bk.freightTerms.toUpperCase();
    return `<div class="doc">${head(house ? 'HOUSE BILL OF LADING' : 'BILL OF LADING', (house ? 'HBL ' + esc(b.hblNo) : 'MBL ' + esc(b.mblNo)) + '<br>Issued by ' + esc(issuer))}
      ${!issued ? '<p><span class="stamp">DRAFT</span></p>' : `<p><span class="stamp">${esc(type.toUpperCase().includes('SEAWAY') ? 'SEAWAY BILL — NON NEGOTIABLE' : 'ORIGINAL')}</span></p>`}
      <div class="boxes">${box('Shipper', esc(shipper))}${box('B/L no.', '<b class="mono">' + esc(house ? b.hblNo : b.mblNo) + '</b><br>Booking ' + esc(bk.no))}${box('Consignee', esc(cons))}${box('Notify party', esc(notify))}${box('Vessel / voyage', esc(bk.vessel + ' / ' + bk.voyage))}${box('Port of loading', esc(OPS.portName(j.pol)))}${box('Port of discharge', esc(OPS.portName(j.pod)))}${box('Place of delivery', esc(house && s.direction === 'import' ? j.pod + ' (CY) — door delivery arranged separately' : j.pod))}</div>
      <table style="margin-top:8px"><thead><tr><th>Container / seal</th><th>Packages</th><th>Description of goods</th><th class="num">Gross kg</th><th class="num">CBM</th></tr></thead><tbody><tr><td>${esc(e.containerNo)} / ${esc(e.seal)}<br>${esc(e.type)}</td><td>${j.packages} ${esc(j.pkgType.toUpperCase())}</td><td>SHIPPER’S LOAD, STOW & COUNT<br>SAID TO CONTAIN: ${esc(j.commodity.toUpperCase())}<br>HS ${esc(j.hs)}</td><td class="num">${TS.num(j.grossKg, 0)}</td><td class="num">${TS.num(j.cbm)}</td></tr></tbody></table>
      <p><b>${ft}</b> · Shipped on board ${issued ? TS.fmtDate(b.issuedOn, false) : '—'} · Number of originals: ${type.toUpperCase().includes('SEAWAY') ? '0 (seaway)' : 'THREE (3)'}</p>${footer}</div>`;
  }

  function an(s) {
    const a = s.documents.arrivalNotice, q = s.quotation, sc = OPS.sc(s);
    const act = q.lines.filter((l) => l.group !== 'optional' || q.insurance);
    return `<div class="doc">${head('ARRIVAL NOTICE', 'HBL ' + esc(s.documents.bl.hblNo) + ' · ' + TS.fmtDate(a.date, false))}
      <p><b>To:</b> ${party(sc.consignee)}</p>${kv([['Vessel', esc(s.booking.connectingVessel || s.booking.vessel)], ['ETA Beirut', '<b>' + TS.fmtDate(a.eta) + '</b>'], ['Container', esc(s.equipment.containerNo + ' / ' + s.equipment.type)], ['Packages / weight', s.jobFile.packages + ' ' + esc(s.jobFile.pkgType) + ' / ' + TS.num(s.jobFile.grossKg, 0) + ' kg'], ['Free time', a.freeDays + ' days from discharge']])}
      <table style="margin-top:8px"><thead><tr><th>Charges due before release</th><th class="num">USD</th></tr></thead><tbody>${act.map((l) => `<tr><td>${esc(l.desc.en || l.desc)}</td><td class="num">${TS.num(l.sell)}</td></tr>`).join('')}<tr><td>VAT 11%</td><td class="num">${TS.num(q.totals.vat)}</td></tr><tr class="total"><td>TOTAL</td><td class="num">${TS.num(a.totalDue)}</td></tr></tbody></table>
      <p><b>Container deposit:</b> USD ${TS.num(a.deposit, 0)} (refundable) to the line’s agent before the D/O.<br><b>Documents for customs:</b> commercial invoice, packing list, certificate of origin, commercial registration & VAT certificate.</p>${footer}</div>`;
  }

  function dor(s) {
    const r = s.release;
    return `<div class="doc">${head('DELIVERY ORDER', esc(r.doNo) + ' · ' + esc(s.booking.carrierName) + ' agency Beirut')}${kv([['To', 'Beirut Container Terminal / Customs'], ['Please deliver to', esc(co().name) + ' or order (for ' + esc(OPS.sc(s).consignee.name) + ')'], ['B/L', esc(s.documents.bl.mblNo) + ' (seaway)'], ['Vessel', esc(s.booking.connectingVessel)], ['Container / seal', esc(s.equipment.containerNo + ' / ' + s.equipment.seal)], ['Packages', s.jobFile.packages + ' ' + esc(s.jobFile.pkgType)], ['Issued', TS.fmtDate(r.doDate)], ['Valid until', TS.fmtDate(TS.addDays(r.doDate, 10))], ['Empty return depot', esc(OPS.sc(s).depot)], ['Deposit received', 'USD ' + TS.num(r.deposit, 0)]])}<p><small>Subject to customs release. Detention as per line tariff after free time.</small></p>${footer}</div>`;
  }

  function invoice(s) {
    const i = s.closing.invoice;
    return `<div class="doc">${head('TAX INVOICE', esc(i.no) + ' · ' + TS.fmtDate(i.date, false))}<p><b>Bill to:</b> ${party(i.customer)}<br>${esc(i.customer.reg || '')}</p><p>Job ${esc(s.id)} · HBL ${esc(s.documents.bl.hblNo)} · ${esc(s.equipment.containerNo)}</p>
      <table><thead><tr><th>Code</th><th>Description</th><th>VAT</th><th class="num">USD</th></tr></thead><tbody>${i.lines.map((l) => `<tr><td>${esc(l.code)}</td><td>${esc(l.desc)}</td><td>${l.vat ? '11%' : 'exempt'}</td><td class="num">${TS.num(l.amount)}</td></tr>`).join('')}
      <tr><td></td><td>VAT 11% on USD ${TS.num(i.vatBase)}</td><td></td><td class="num">${TS.num(i.vat)}</td></tr><tr class="total"><td></td><td>TOTAL</td><td></td><td class="num">${TS.num(i.total)}</td></tr></tbody></table>
      <p>VAT in LBP: ${TS.num(i.vatLBP, 0)} (at LBP ${TS.num(i.lbpRate, 0)}/USD — sample rate).</p>${footer}</div>`;
  }

  function jobsheet(s) {
    return `<div class="doc">${head('SHIPMENT TIMELINE', esc(s.id))}<ul class="timeline">${s.milestones.map((m) => `<li class="done"><b>${TS.fmtDate(m.date)}</b> — ${esc(m.label)}</li>`).join('') || '<li>—</li>'}</ul>${s.closing && s.closing.jobCosting ? kv([['Revenue', 'USD ' + TS.num(s.closing.jobCosting.revenue)], ['Cost', 'USD ' + TS.num(s.closing.jobCosting.costTotal)], ['Job profit', '<b>USD ' + TS.num(s.closing.jobCosting.profit) + '</b> (' + TS.num(s.closing.jobCosting.margin, 1) + '%)']]) : ''}${footer}</div>`;
  }

  OPS.docs = {
    list(s) {
      const d = [{ id: 'timeline', name: L('Timeline', 'الخط الزمني'), html: jobsheet }];
      if (s.jobFile && s.jobFile.pol) d.push({ id: 'job', name: L('Job file', 'ملف العملية'), html: jobfile });
      if (s.quotation) d.push({ id: 'quote', name: L('Quotation', 'عرض السعر'), html: quotation });
      if (s.booking) d.push({ id: 'so', name: L('Booking confirmation (SO)', 'تأكيد الحجز'), html: so });
      if (s.equipment && s.equipment.vgm) d.push({ id: 'vgm', name: 'VGM', html: vgm });
      if (s.documents && s.documents.si) d.push({ id: 'si', name: L('Shipping instructions', 'تعليمات الشحن'), html: si });
      if (s.documents && s.documents.bl && s.documents.bl.mblNo) {
        d.push({ id: 'mbl', name: L('Master B/L', 'البوليصة الرئيسية'), html: (x) => bl(x, false) });
        d.push({ id: 'hbl', name: L('House B/L', 'بوليصة الوكيل'), html: (x) => bl(x, true) });
      }
      if (s.documents && s.documents.arrivalNotice && s.direction === 'import') d.push({ id: 'an', name: L('Arrival notice', 'إشعار الوصول'), html: an });
      if (s.release && s.release.doNo) d.push({ id: 'do', name: L('Delivery order', 'إذن التسليم'), html: dor });
      if (s.closing && s.closing.invoice) d.push({ id: 'inv', name: L('Tax invoice', 'الفاتورة الضريبية'), html: invoice });
      return d;
    },
  };
})();
